version: "3"
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn dev
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3000:3000
